# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wgu-e2AoasL47umMrRWil4W1-Tqn3Ndm
"""

# Windows/VS Code: place the dataset ZIP in the same folder as this Python file.
# No Google Colab upload is needed.

import zipfile
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
zip_path = os.path.join(BASE_DIR, "image_captioning_500_synthetic.zip")
extract_path = os.path.join(BASE_DIR, "image_captioning_500")

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

import os

for root, dirs, files in os.walk(extract_path):
    print(root)
    print("Number of files:", len(files))
    print()

for root, dirs, files in os.walk(extract_path):
    if len(files) > 0:
        print(root)

for root, dirs, files in os.walk(extract_path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

import pandas as pd

caption_path = os.path.join(extract_path, "captions_500.csv")

df = pd.read_csv(caption_path)

print(df.head())

print("Total captions:", len(df))

print(df.columns)

image_folder = os.path.join(extract_path, "images")

images = [
    file for file in os.listdir(image_folder)
    if file.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Total images:", len(images))

image_names = set(images)
caption_names = set(df["image"])

matched_images = image_names.intersection(caption_names)

print("Total images:", len(image_names))
print("Total captions:", len(caption_names))
print("Matched images:", len(matched_images))

import pandas as pd
import numpy as np
import os
from PIL import Image

import os

for root, dirs, files in os.walk(BASE_DIR):
    if files:
        print("Folder:", root)
        print("Files:", files[:10])
        print()

import pandas as pd
import os

image_folder = os.path.join(extract_path, "images")
caption_path = os.path.join(extract_path, "captions_500.csv")

df = pd.read_csv(caption_path)
images = os.listdir(image_folder)

print("Total images:", len(images))
print("Total captions:", len(df))
print(df.head())

image_names = set(images)
caption_names = set(df["image"])

matched_images = image_names.intersection(caption_names)

print("Total images:", len(image_names))
print("Total captions:", len(caption_names))
print("Matched images:", len(matched_images))

import re

def clean_caption(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["clean_caption"] = df["caption"].apply(clean_caption)

print(df[["caption", "clean_caption"]].head())

df["final_caption"] = df["clean_caption"].apply(
    lambda x: "<start> " + x + " <end>"
)

print(df[["image", "final_caption"]].head())

from PIL import Image
import os

processed_folder = os.path.join(BASE_DIR, "processed_images")

os.makedirs(processed_folder, exist_ok=True)

for image_name in images:
    image_path = os.path.join(image_folder, image_name)

    img = Image.open(image_path)
    img = img.convert("RGB")
    img = img.resize((224, 224))

    img.save(os.path.join(processed_folder, image_name))

print("Images resized successfully")
print("Total processed images:", len(os.listdir(processed_folder)))

print("Total images:", len(images))
print("Total captions:", len(df))
print("Processed images:", len(os.listdir(processed_folder)))

print("\nSample caption:")
print(df["final_caption"].iloc[0])

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input

from tensorflow.keras.applications import VGG16

model = VGG16(weights="imagenet", include_top=False)

print("VGG16 model loaded successfully")

from tensorflow.keras.preprocessing.image import load_img, img_to_array

image_name = images[0]
image_path = os.path.join(processed_folder, image_name)

img = load_img(image_path, target_size=(224, 224))
img = img_to_array(img)
img = np.expand_dims(img, axis=0)
img = preprocess_input(img)

print("Image prepared successfully")
print("Image:", image_name)
print("Image shape:", img.shape)

features = model.predict(img)

print("Features extracted successfully")
print("Feature shape:", features.shape)

features = features.reshape(features.shape[0], -1)

print("Features converted successfully")
print("New feature shape:", features.shape)

all_features = {}

for image_name in images:
    image_path = os.path.join(processed_folder, image_name)

    img = load_img(image_path, target_size=(224, 224))
    img = img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)

    feature = model.predict(img, verbose=0)
    feature = feature.reshape(-1)

    all_features[image_name] = feature

print("Features extracted for all images:", len(all_features))

import pickle

with open(os.path.join(BASE_DIR, "image_features.pkl"), "wb") as f:
    pickle.dump(all_features, f)

print("Features saved successfully")

from tensorflow.keras.preprocessing.text import Tokenizer

captions = df["final_caption"].tolist()

print("Total captions:", len(captions))
print("First caption:", captions[0])

tokenizer = Tokenizer()
tokenizer.fit_on_texts(captions)

print("Tokenizer created successfully")
print("Total words:", len(tokenizer.word_index))

caption_sequences = tokenizer.texts_to_sequences(captions)

print("Captions converted into sequences")
print("First sequence:", caption_sequences[0])

max_length = max(len(seq) for seq in caption_sequences)

print("Maximum caption length:", max_length)

print("Word to number mapping:")
print(tokenizer.word_index)

from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_sequences = pad_sequences(
    caption_sequences,
    maxlen=max_length,
    padding="post"
)

print("Captions padded successfully")
print("Padded shape:", padded_sequences.shape)
print("First padded sequence:", padded_sequences[0])

print("Total image features:", len(all_features))
print("Feature size:", all_features[images[0]].shape)

import numpy as np

image_features = np.array([all_features[name] for name in images])

print("Image features prepared")
print("Shape:", image_features.shape)

from tensorflow.keras.layers import Input, Dense

image_input = Input(shape=(25088,))
image_dense = Dense(256, activation="relu")(image_input)

print("CNN input layer created successfully")

from tensorflow.keras.layers import Embedding, LSTM

caption_input = Input(shape=(max_length,))

caption_embedding = Embedding(
    input_dim=len(tokenizer.word_index) + 1,
    output_dim=256
)(caption_input)

caption_lstm = LSTM(256)(caption_embedding)

print("LSTM caption input created successfully")

from tensorflow.keras.layers import Concatenate

combined = Concatenate()([image_dense, caption_lstm])

print("Image and caption features combined successfully")

from tensorflow.keras.layers import Dropout

combined = Dropout(0.5)(combined)
output = Dense(len(tokenizer.word_index) + 1, activation="softmax")(combined)

print("Output layer created successfully")

from tensorflow.keras.models import Model

caption_model = Model(
    inputs=[image_input, caption_input],
    outputs=output
)

print("CNN + LSTM model created successfully")

caption_model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

print("Model compiled successfully")

X_image = []
X_caption = []
y = []

for i in range(len(padded_sequences)):
    sequence = padded_sequences[i]

    for j in range(1, len(sequence)):
        X_image.append(image_features[i])
        X_caption.append(sequence[:j])
        y.append(sequence[j])

print("Training sequences created")
print("Total sequences:", len(y))

X_image = np.array(X_image)

X_caption = pad_sequences(
    X_caption,
    maxlen=max_length,
    padding="post"
)

y = np.array(y)

print("Training data prepared successfully")
print("Image input shape:", X_image.shape)
print("Caption input shape:", X_caption.shape)
print("Target shape:", y.shape)

history = caption_model.fit(
    [X_image, X_caption],
    y,
    epochs=5,
    batch_size=32,
    verbose=1
)

print("Model training completed")

def generate_caption(image_name):
    image_feature = all_features[image_name]
    image_feature = np.expand_dims(image_feature, axis=0)

    caption = [tokenizer.word_index["start"]]

    for i in range(max_length - 1):
        sequence = pad_sequences([caption], maxlen=max_length, padding="post")

        prediction = caption_model.predict(
            [image_feature, sequence],
            verbose=0
        )

        next_word = np.argmax(prediction[0])

        if next_word == 0:
            break

        word = tokenizer.index_word.get(next_word, "")

        if word == "end":
            break

        caption.append(next_word)

    words = [tokenizer.index_word.get(i, "") for i in caption[1:]]
    return " ".join(words)

test_image = images[0]

generated_caption = generate_caption(test_image)

print("Image:", test_image)
print("Generated Caption:", generated_caption)

from IPython.display import display
from PIL import Image

test_image_path = os.path.join(processed_folder, test_image)

display(Image.open(test_image_path))
print("Generated Caption:", generated_caption)

test_image = images[10]

generated_caption = generate_caption(test_image)

print("Test Image:", test_image)
print("Generated Caption:", generated_caption)

from IPython.display import display
from PIL import Image

test_image_path = os.path.join(processed_folder, test_image)

display(Image.open(test_image_path))
print("Generated Caption:", generated_caption)

import matplotlib.pyplot as plt

plt.plot(history.history["accuracy"])
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Model Training Accuracy")
plt.show()

plt.plot(history.history["loss"])
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Model Training Loss")
plt.show()

for i in range(5):
    test_image = images[i]
    caption = generate_caption(test_image)

    print("Image:", test_image)
    print("Generated Caption:", caption)
    print("-" * 50)

from IPython.display import display
from PIL import Image

for i in range(5):
    test_image = images[i]
    image_path = os.path.join(processed_folder, test_image)

    display(Image.open(image_path))
    print("Image:", test_image)
    print("Generated Caption:", generate_caption(test_image))
    print("-" * 50)

caption_model.save(os.path.join(BASE_DIR, "image_captioning_model.h5"))

print("Model saved successfully")

import pickle

with open(os.path.join(BASE_DIR, "tokenizer.pkl"), "wb") as f:
    pickle.dump(tokenizer, f)

print("Tokenizer saved successfully")

import pickle

with open(os.path.join(BASE_DIR, "image_features.pkl"), "wb") as f:
    pickle.dump(all_features, f)

print("Image features saved successfully")

import os

print("Model file:", os.path.exists(os.path.join(BASE_DIR, "image_captioning_model.h5")))
print("Tokenizer file:", os.path.exists(os.path.join(BASE_DIR, "tokenizer.pkl")))
print("Image features file:", os.path.exists(os.path.join(BASE_DIR, "image_features.pkl")))

